name: Eleventy Build And Publish
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: '18.20.6'

      - name: Build
        uses: TartanLlama/actions-eleventy@master

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: _site 
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}